server.port=9090

#eureka server configuration in application.properties

spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=Method=POST,GET

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**


# Logging
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.file.name=logs/api-gateway.log

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n