server.port=9090

#eureka server configuration in application.properties

spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=Method=POST,GET

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents,ratelimiters,retries,bulkheads
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true