server.port=8082

#eureka server configuration in application.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/order_microservice
spring.datasource.username=postgres
spring.datasource.password=dine
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

resilience4j.circuitbreaker.instances.USER-SERVICE.slidingWindowSize=10
resilience4j.circuitbreaker.instances.USER-SERVICE.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.USER-SERVICE.failureRateThreshold=50
resilience4j.circuitbreaker.instances.USER-SERVICE.waitDurationInOpenState=2s
resilience4j.circuitbreaker.instances.USER-SERVICE.permittedNumberOfCallsInHalfOpenState=1

resilience4j.ratelimiter.instances.USER-SERVICE.limitForPeriod=5
resilience4j.ratelimiter.instances.USER-SERVICE.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.USER-SERVICE.timeoutDuration=0

resilience4j.retry.instances.USER-SERVICE.maxAttempts=2
resilience4j.retry.instances.USER-SERVICE.waitDuration=200ms

resilience4j.timelimiter.instances.USER-SERVICE.timeoutDuration=3s
resilience4j.timelimiter.instances.USER-SERVICE.cancelRunningFuture=true


management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents,ratelimiters,retries,bulkheads
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true


# Logging
logging.level.root=INFO
logging.level.com.orderservice=DEBUG
logging.file.name=logs/order-service.log

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [CorrelationId=%X{correlationId}] %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [CorrelationId=%X{correlationId}] %logger{36} - %msg%n