server.port=8081

#eureka server configuration in application.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/user_microservice
spring.datasource.username=postgres
spring.datasource.password=dine
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

