spring.application.name=eureka-server

server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Logging
logging.level.root=INFO
logging.level.com.netflix.eureka=INFO
logging.file.name=logs/eureka-server.log

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n